-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS ServiceUser CASCADE;
DROP TABLE IF EXISTS Sample CASCADE;
DROP TABLE IF EXISTS SampleTag CASCADE;
DROP TABLE IF EXISTS Tag CASCADE;
DROP TABLE IF EXISTS Project CASCADE;
DROP TABLE IF EXISTS ProjectSample CASCADE;
--DROP TABLE IF EXISTS Comment CASCADE;